" This main file just sets the list of plugins and the configuration variables
" for them. Check the plugin folder for more interesting functionality.

" List of plugins {{{
" These are the first lines of every vimrc.
set nocompatible
filetype off
" Prepare Vundle with XDG-compliant directories
set runtimepath+=$XDG_CONFIG_HOME/vim/bundle/Vundle.vim
call vundle#begin(expand("$XDG_CONFIG_HOME/vim/bundle"))

Plugin 'gmarik/Vundle.vim'
" Vim general enhancements
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-unimpaired'
Plugin 'kana/vim-textobj-user'
" Use system fzf if installed
if isdirectory("/usr/local/opt/fzf")
  set rtp+=/usr/local/opt/fzf
else
  Plugin 'junegunn/fzf'
end
Plugin 'junegunn/fzf.vim'
Plugin 'nelstrom/vim-textobj-rubyblock'
Plugin 'rizzatti/dash.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'qpkorr/vim-bufkill'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'chrisbra/Recover.vim'
Plugin 'tpope/vim-eunuch'
Plugin 'itchyny/lightline.vim'
" VimWiki / note taking stuff
Plugin 'vimwiki/vimwiki'
Plugin 'git@github.com:CGamesPlay/vim-zettel.git'
set rtp+=/Users/rpatterson/Projects/pilikino/vim
" Language syntaxes
"Plugin 'pangloss/vim-javascript'
"Plugin 'mxw/vim-jsx'
Plugin 'dag/vim-fish'
Plugin 'groenewege/vim-less'
Plugin 'jparise/vim-graphql'
Plugin 'leafgarland/typescript-vim'
"Plugin 'peitalin/vim-jsx-typescript'
" Language-specific tools
Plugin 'prettier/vim-prettier'
Plugin 'dense-analysis/ale'
Plugin 'Quramy/tsuquyomi' " Typescript
if version >= 801
  " This isn't the precisely correct version number, but close enough
  Plugin 'fatih/vim-go'
end
" Color schemes
Plugin 'altercation/vim-colors-solarized'
Plugin 'tjammer/blandon.vim'
Plugin 'tjammer/blayu.vim'
Plugin 'jonasmao/vim-color-lost-shrine'

call vundle#end()
" Vundle has reapplied the vim-default config directory to the rtp, so we
" make sure to reorder or override into its place.
set rtp-=$HOME/.vim
set rtp-=$XDG_CONFIG_HOME/vim
set rtp^=$XDG_CONFIG_HOME/vim

" Finally, enable autoloading features
syntax enable
filetype plugin indent on

" See :help matchit
packadd! matchit

" Disable netrw, because:
" - gx doesn't work https://github.com/vim/vim/issues/4738
" - editing directories is never what I want to do
" - netrw buffers can't be closed with BW
" - I don't presently edit any files on remote servers
let g:loaded_netrw = 1

" }}}
" Configuration variables for plugins {{{

let g:javascript_plugin_flow = 1
let g:prettier#config#single_quote = 'false'
let g:prettier#config#bracket_spacing = 'true'
let g:prettier#config#jsx_bracket_same_line = 'false'
let g:prettier#quickfix_enabled = 0
let g:prettier#autoformat = 0
let g:prettier#write_on_save = 1
let g:ale_sign_column_always = 1
let g:ale_set_highlights = 0
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_open_list = 0
let g:ale_fixers = {
      \'ruby': ['rubocop'],
      \}
let g:ale_linters = {
      \'graphql': ['gqlint'],
      \}
let g:ale_echo_msg_format = '%linter% says %s'
let g:ale_javascript_eslint_suppress_eslintignore = 1
let g:ale_javascript_eslint_suppress_missing_config = 1
" Prevent editorconfig from touching these buffers
let g:EditorConfig_exclude_patterns = ['fugitive://.\*']
let g:RecoverPlugin_Delete_Unmodified_Swapfile = 1
let g:tsuquyomi_disable_quickfix = 1
" The default go rename doesn't work in modules.
" https://github.com/fatih/vim-go/issues/2366#issuecomment-583033166
let g:go_rename_command = 'gopls'
" vim-go has a bug with folding
"let g:go_fmt_experimental = 1
let g:go_fmt_command = 'gopls'

" }}}
