" Welcome to my vimrc!

" Vundle setup {{{

" vim: foldmethod=marker fdl=0

set nocompatible
filetype off
set runtimepath+=$XDG_CONFIG_HOME/vim/bundle/Vundle.vim

" }}}

" Plugin configuration {{{

if isdirectory("/usr/local/opt/fzf")
  set rtp+=/usr/local/opt/fzf
end

call vundle#begin(expand("$XDG_CONFIG_HOME/vim/bundle"))

Plugin 'gmarik/Vundle.vim'
" Vim general enhancements
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-unimpaired'
Plugin 'altercation/vim-colors-solarized'
Plugin 'kana/vim-textobj-user'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'nelstrom/vim-textobj-rubyblock'
Plugin 'rizzatti/dash.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'qpkorr/vim-bufkill'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'chrisbra/Recover.vim'
Plugin 'tpope/vim-eunuch'
" Language syntaxes
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'dag/vim-fish'
Plugin 'groenewege/vim-less'
Plugin 'jparise/vim-graphql'
Plugin 'leafgarland/typescript-vim'
Plugin 'peitalin/vim-jsx-typescript'
if version >= 801
  " This isn't the precisely correct version number, but close enough
  Plugin 'fatih/vim-go'
end
" Language-specific tools
Plugin 'prettier/vim-prettier'
Plugin 'w0rp/ale'

runtime macros/matchit.vim

" End of Vundle config
call vundle#end()
syntax on
filetype plugin indent on

" Set up plugin defaults

let g:javascript_plugin_flow = 1
let g:prettier#config#single_quote = 'false'
let g:prettier#config#bracket_spacing = 'true'
let g:prettier#config#jsx_bracket_same_line = 'false'
let g:prettier#quickfix_enabled = 0
let g:prettier#autoformat = 0
let g:prettier#write_on_save = 1
let g:ale_sign_column_always = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_open_list = 'on_save'
let g:ale_fixers = {
      \'ruby': ['rubocop'],
      \}
let g:ale_linters = {
      \'graphql': ['gqlint'],
      \}
let g:ale_echo_msg_format = '%linter% says %s'
let g:ale_javascript_eslint_suppress_eslintignore = 1
let g:ale_javascript_eslint_suppress_missing_config = 1
" Prevent editorconfig from touching these buffers
let g:EditorConfig_exclude_patterns = ['fugitive://.\*']
let g:RecoverPlugin_Delete_Unmodified_Swapfile = 1

" }}}

" Core behavioral settings {{{

" Backup files are annoying
set nobackup

" I use fish, but startup is super slow and I don't care about the differences
" in vim.
set shell=/bin/sh

" This means a buffer will still be loaded even if it isn't displayed. Use :ls
" and :bd to manage
set hidden
" Automatically reload files when modified by other programs
set autoread

" smartcase is case-sensitive iff your search includes a capital letter
set ignorecase smartcase incsearch hlsearch

" Use the tab-completion (for files) that I'm used to in bash.
set wildmode=list:longest

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Tabs are 4 spaces wide, but we use spaces instead. shiftwidth is for
" autoindent, softtabstop is for when I press tab
set tabstop=4 expandtab shiftwidth=2 softtabstop=2

" In general, 80col
set textwidth=80
augroup formatting
  au!
  " Don't automatically break long lines while typing.
  au BufEnter * setlocal formatoptions+=l
augroup END
" default for unknown
"set formatoptions=tcqj
" default for code
"set formatoptions=jcroql

" Wrap long lines by showing a symbol at the beginning of the next line and
" indenting.
set linebreak breakindent breakindentopt=shift:4
let &showbreak = "\u21b3 "


" Check .git/tags for tags files, in all parent directories.
set tags^=./.git/tags;

" vim-go has a bug with folding
let g:go_fmt_experimental = 1

augroup folding
  au!
  " Default to syntax folding, but no folds enabled by default
  autocmd GUIEnter * set foldmethod=syntax foldlevelstart=99
  " Don't screw up folds when inserting text that might affect them, until
  " leaving insert mode. Foldmethod is local to the window. Protect against
  " screwing up folding when switching between windows.
  autocmd InsertEnter * if !exists('w:last_fdm') | let w:last_fdm=&foldmethod | setlocal foldmethod=manual | endif
  autocmd InsertLeave,WinLeave * if exists('w:last_fdm') | let &l:foldmethod=w:last_fdm | unlet w:last_fdm | endif
augroup END

" }}}

" Core display settings {{{

if version >= 703
  " Show line numbers in the gutter
  set number
  " I prefer this, but it slows the UI too much to be useful.
  "set relativenumber
end

" I like to know what file I'm editing even when I'm only editing one.
set laststatus=2

" Display the caret position at bottom of screen
set ruler

" Shows the partial command in the last line
set showcmd

if version >= 703
  " Display a line at the 81st column
  set colorcolumn=+1
end

" Highlight tab literals and trailing spaces
set list listchars=tab:\ \ ,trail:\ 

" Don't update the screen while running macros
set lazyredraw

" Always show the sign column, so it doesn't flicker in when I load files
if exists('+signcolumn')
  set signcolumn=yes
end

" Ensure there's some context around search results
set scrolloff=5

" }}}

" Pretty display settings (colors, GUI) {{{

" Main color settings
if !has("gui_macvim")
  set guifont="Anonymous Pro":h14
else
  set guifont=Consolas:h14,Anonymous_Pro:h14
end
set linespace=2
colors solarized

" e: tab bar; g: show disabled menu items gray; m: use menubar
set guioptions=eg

if has("gui_macvim")
  " Transparency rocks, but only in small quantities
  set transparency=2
  " Fullscreen fills entire screen, retains transparency setting
  set fuopt+=maxhorz,background:Normal
endif

augroup initial_winsize " {{{
  au!
  " Initial window size. 171 is just wide enough for 2 vertical splits of 80
  " columns plus chrome. 999 is quite tall.
  au GUIEnter * :2Cols
augroup END " }}}

augroup os_appearance " {{{
  au!
  " Switch to a dark background in Dark Mode.
  if exists('v:os_appearance')
    function! s:SyncOSAppearance()
      if v:os_appearance % 2 == 0
        set background=light
      else
        set background=dark
      endif
      redraw!
    endfunction
    au GUIEnter * call s:SyncOSAppearance()
    au OSAppearanceChanged * call s:SyncOSAppearance()
  else
    " Default to light bg
    set background=light
  endif
augroup END " }}}

" }}}

" Input settings {{{

" Use , as a custom leader key.
let mapleader=","

" Enable the mouse in normal mode
set mouse=n

" I was accidentally pasting too much
map <MiddleMouse> <Nop>

" Select mode is for Notepad users.
set selectmode=

" F2 will switch to paste mode, which will disable auto-indent, among other
" things.
set pastetoggle=<F2>

" }}}

" Key bindings (noremaps) {{{

" Unbind arrow keys to force yourself to break that habit when you are just
" getting started.
" noremap <Left> <Nop>
" noremap <Right> <Nop>
" noremap <Up> <Nop>
" noremap <Down> <Nop>
" inoremap <Left> <Nop>
" inoremap <Right> <Nop>
" inoremap <Up> <Nop>
" inoremap <Down> <Nop>

" Enter command mode by pressing ; instead of :
noremap ; :

" I don't really use space, and have , and ; remapped
noremap <Space> ;
noremap <S-Space> ,

" Exit insert mode by typing jk. Trust me, you never need to type jk.
inoremap jk <Esc>
" jk can be used to exit from terminal mode just as well.
if exists(':tnoremap')
  tnoremap jk <C-\><C-n>
endif

" Love me some emacs-style shortcuts
inoremap <C-a> <Esc>I
inoremap <C-e> <Esc>A
inoremap <C-d> <Delete>
cnoremap <C-a> <Home>
cnoremap <C-e> <End>
cnoremap <C-d> <Delete>

" Window nav
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

" Instead of closing the window, wipe out the current buffer, but switch to the
" previous buffer before doing so to preserve window splits.
if has("gui_macvim")
    noremap <D-w> :BD<CR>
else
    noremap <A-w> :BD<CR>
end

" Arrow keys scroll view in normal mode
noremap <Up> <C-y>
noremap <Down> <C-e>

" jk should scroll by visible lines
nnoremap <silent> j gj
nnoremap <silent> k gk
" and gj/gk should scroll by actual lines
nnoremap <silent> gj j
nnoremap <silent> gk k

" n / N normally follow / reverse the current search direction. I want n to
" always go forward, and N always backward, regardless of the current search
" direction. (This means #n will always take you to where you just were.)
nnoremap n /<cr>
nnoremap N ?<cr>

" Use %% in command mode to get the directory of the current file.
cnoremap %% <C-R>=expand('%:h').'/'<cr>

" Command-R will save and then refresh the active Chrome window, why not
nnoremap <D-r> :wa\|!osascript -e 'tell application "Google Chrome" to set URL of active tab of its first window to "javascript:void(typeof Jupyter \!== \"undefined\" ? Jupyter.notebook.execute_all_cells() : location.reload())"'<CR><CR>

" }}}

" Shortcuts (maps) {{{

" Toggle fullscreen mode on command-enter
nmap <silent> <D-CR> :set fullscreen!<CR>

" Q normally switches to ex mode, but I don't use that
map Q gq

" ,/ will turn off search highlighting until you search again.
nmap <silent> <leader>/ :nohlsearch<CR>

" "Fold tag", useful for XML/HTML
nnoremap <leader>ft Vatzf

" Search for current word with fugitive
nmap <leader>g :Ggrep! -w '<C-r><C-w>'<CR>
" Search for current selection with fugitive
vmap <leader>g y:Ggrep! '<C-r>"'<CR>

" Jump to an open file (fzf)
nmap <C-B> :Buffers<CR>
" Jump to a file in git, include untracked files (fzf)
nmap <C-P> :GFiles -co --exclude-standard<CR>
if has("gui_macvim")
  " Command palette (fzf)
  nmap <D-p> :Commands<CR>
  " Keyboard shortcut palette, in case you forget one (fzf)
  nmap <D-P> :Maps<CR>
else
  nmap <A-p> :Commands<CR>
  nmap <A-P> :Maps<CR>
end

" Split the buffer or window left, right, up, or down
nmap <leader>sh  :leftabove  vnew<CR>
nmap <leader>sj  :rightbelow new<CR>
nmap <leader>sk  :leftabove  new<CR>
nmap <leader>sl  :rightbelow vnew<CR>
nmap <leader>swh :topleft    vnew<CR>
nmap <leader>swj :botright   new<CR>
nmap <leader>swk :topleft    new<CR>
nmap <leader>swl :botright   vnew<CR>

" Dash lookups
nmap <silent> <leader>d <Plug>DashSearch

" }}}

" Custom commands {{{

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
command! DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
        \ | wincmd p | diffthis

" This doesn't work right....
if &term == "screen" || &term == "xterm"
  if &term == "screen"
    set t_ts=k
    set t_fs=\
  endif
  set title
  let &titlestring = "vim " . pathshorten(expand("%:~:.:f"))
  au BufEnter * let &titlestring = "vim " . pathshorten(expand("%:~:.:f"))
endif

" Resize my window to fit N columns of 81 columns with 6 gutter columns each
" plus (n - 1) separator bars, and be max height
function! SetCols(n)
  let cols = a:n * 88 - 1
  exec "set columns=" . cols . " lines=999"
  normal =
endfunction
command! -count=1 Cols call SetCols(<count>)

" Quick way to toggle prettier write_on_save
command! PrettierDisable let g:prettier#write_on_save = 0
command! PrettierEnable let g:prettier#write_on_save = 1

" Edit this file using :e $VIMRC or :vsp $VIMRC or whatever
let $VIMRC = expand('<sfile>')

augroup personal " {{{
  au!

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  au BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") && &ft != 'gitcommit' |
    \   exe "normal! g`\"" |
    \ endif

  " Automatically open the location list after performing an grep.
  au QuickFixCmdPost *grep* botright cwindow

  " Remove trailing spaces when leaving insert mode
  au InsertLeave * '[,']s/\s\+$//e|normal `^

  " Close the location list when closing the parent window
  au BufWinLeave * lclose
augroup END " }}}

" }}}

" File type-specific {{{

augroup ft_phpt " {{{
  au!

  " phpt files are php files in disguise
  au BufNewFile,BufRead *.phpt setlocal filetype=php
augroup END " }}}

augroup ft_javascript " {{{
  au!
  " CommonJS modules omit the .js, so this allows gf to work
  au FileType javascript setlocal suffixesadd=.js
  au BufNewFile,BufRead *.tsx,*.jsx set filetype=typescript.tsx
augroup END " }}}

augroup ft_text " {{{
  au!

  " For all text files set 'textwidth' to 78 characters.
  au FileType text setlocal textwidth=78
augroup END " }}}

augroup ft_cfolding " {{{
  au!

  au FileType javascript,java,c,php,css setlocal foldmethod=marker
  au FileType javascript,java,c,php,css setlocal foldmarker={,}
  au FileType javascript,java,c,php,css setlocal foldlevel=999
augroup END " }}}

augroup ft_python " {{{
  au!

  au FileType python setlocal sw=4 sts=4 ts=4
  au FileType python setlocal foldmethod=indent
augroup END " }}}

augroup ft_ruby " {{{
  au!

  au FileType ruby setlocal foldmethod=marker
  if has("balloon_eval")
    au FileType ruby setlocal balloonexpr=
  end
augroup END " }}}

augroup ft_sh " {{{
  au!
  " Disable automatic word wrapping in shell scripts
  au FileType sh setlocal tw=0
augroup END " }}}

augroup prettier " {{{
  au!

  autocmd BufWritePre *.js,*.json,*.css,*.scss,*.less,*.graphql,*.ts,*.tsx if g:prettier#write_on_save | Prettier | endif
augroup END

" }}}

augroup ft_go " {{{
  au!

  au FileType go setlocal nolist noexpandtab sw=4 sts=4 ts=4
augroup END

" }}}

" }}}
