" Welcome to my vimrc!

" Vundle setup {{{

" vim: foldmethod=marker

set nocompatible
filetype off
set runtimepath+=~/.vim/bundle/Vundle.vim

" }}}

" Plugin configuration {{{

call vundle#begin()

Plugin 'altercation/vim-colors-solarized'
Plugin 'dag/vim-fish'
Plugin 'gmarik/Vundle.vim'
Plugin 'groenewege/vim-less'
Plugin 'kana/vim-textobj-user'
Plugin 'kien/ctrlp.vim'
Plugin 'nelstrom/vim-textobj-rubyblock'
Plugin 'tpope/vim-fugitive'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'pangloss/vim-javascript'
Plugin 'git-time-metric/gtm-vim-plugin'
Bundle 'mxw/vim-jsx'
" Crashes too much
"Plugin 'valloric/YouCompleteMe'

runtime macros/matchit.vim

" End of Vundle config
call vundle#end()
syntax on
filetype plugin indent on

" }}}

" Core behavioral settings {{{

" Backup files are annoying
set nobackup
" set directory to a local path, because swapping over sshfs is really slow.
set directory=~/.vim/swaps//

" Necessary to fix up vim system() calls since I use fish normally.
set shell=/bin/sh

" This means a buffer will still be loaded even if it isn't displayed. Use :ls
" and :bd to manage
set hidden
" Automatically reload files when modified by other programs
set autoread

" smartcase is case-sensitive iff your search includes a capital letter
set ignorecase smartcase incsearch hlsearch

" Use the tab-completion (for files) that I'm used to in bash.
set wildmode=list:longest

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Tabs are 4 spaces wide, but we use spaces instead. shiftwidth is for
" autoindent, softtabstop is for when I press tab
set tabstop=4 expandtab shiftwidth=2 softtabstop=2

" In general, 80col
set textwidth=80

" Ignore node_modules from file searches
set wildignore=*/node_modules/*,*/tmp/*

" }}}

" Core display settings {{{

if version >= 703
  " I like this, some people prefer set number
  " set relativenumber
  " However, it can severly impact UI responsiveness due to excessive screen
  " updates, so disabled for now.
  set number
end

" I like to know what file I'm editing even when I'm only editing one.
set laststatus=2

" Display the caret position at bottom of screen
set ruler

" Shows the partial command in the last line
set showcmd

if version >= 703
  " Display a line at the 81st column
  set colorcolumn=+1
end

" Highlight tab literals and trailing spaces
set list listchars=tab:\ \ ,trail:\ 

" Don't update the screen while running macos
set lazyredraw

" }}}

" Pretty display settings (colors, GUI) {{{

" Main color settings
set guifont=Anonymous_Pro:h13
set background=light
colors solarized

" e: tab bar; g: show disabled menu items gray; m: use menubar
set guioptions=egm

if has("gui_macvim")
  " Transparency rocks, but only in small quantities
  set transparency=2
  " Fullscreen fills entire screen, retains transparency setting
  set fuopt+=maxhorz,background:Normal
endif

augroup initial_winsize " {{{
  au!
  " Initial window size. 171 is just wide enough for 2 vertical splits of 80
  " columns plus chrome. 999 is quite tall.
  au GUIEnter * :set columns=171 lines=999
augroup END " }}}

" }}}

" Input settings {{{

" Use , as a custom leader key.
let mapleader=","

" Enable the mouse in normal mode
set mouse=n

" I was accidentally pasting too much
map <MiddleMouse> <Nop>

" Select mode is for Notepad users.
set selectmode=

" F2 will switch to paste mode, which will disable auto-indent, among other
" things.
set pastetoggle=<F2>

" }}}

" Key bindings (noremaps) {{{

" Unbind arrow keys to force yourself to break that habit when you are just
" getting started.
" noremap <Left> <Nop>
" noremap <Right> <Nop>
" noremap <Up> <Nop>
" noremap <Down> <Nop>
" inoremap <Left> <Nop>
" inoremap <Right> <Nop>
" inoremap <Up> <Nop>
" inoremap <Down> <Nop>

" Enter command mode by pressing ; instead of :
noremap ; :

" I don't really use space, and have , and ; remapped
noremap <Space> ;
noremap <S-Space> ,

" Exit insert mode by typing jk. Trust me, you never need to type jk.
inoremap jk <Esc>
" jk can be used to exit from terminal mode just as well.
if exists(':tnoremap')
  tnoremap jk <C-\><C-n>
endif

" Love me some emacs-style shortcuts
inoremap <C-a> <Esc>I
inoremap <C-e> <Esc>A
inoremap <C-d> <Delete>
cnoremap <C-a> <Home>
cnoremap <C-e> <End>
cnoremap <C-d> <Delete>

" Window nav
noremap <C-h> <C-w>h
if !has("gui_macvim")
  noremap <BS> <C-w>h " This is kludgy, since it means Backspace switches to the left window. But necessary for Neovim.
end
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

" Arrow keys scroll view in normal mode
noremap <Up> <C-y>
noremap <Down> <C-e>

" jk should scroll by visible lines
nnoremap <silent> j gj
nnoremap <silent> k gk
" and gj/gk should scroll by actual lines
nnoremap <silent> gj j
nnoremap <silent> gk k

" Use %% in command mode to get the directory of the current file.
cnoremap %% <C-R>=expand('%:h').'/'<cr>

" Command-R will save and then refresh the active Chrome window, why not
nnoremap <D-r> :wa\|!osascript -e 'tell application "Google Chrome" to set URL of active tab of its first window to "javascript:void(typeof Jupyter \!== \"undefined\" ? Jupyter.notebook.execute_all_cells() : location.reload())"'<CR><CR>

" }}}

" Shortcuts (maps) {{{

" Toggle fullscreen mode on command-enter
nmap <silent> <D-CR> :set fullscreen!<CR>

" Q normally switches to ex mode, but I don't use that
map Q gq

" ,/ will turn off search highlighting until you search again.
nmap <silent> <leader>/ :nohlsearch<CR>

" FSwitch
nmap <leader>s :FSHere<CR>

" Ggrep (fugitive) current word
map <leader>g :Ggrep! -w '<C-r><C-w>'<CR>

" "Fold tag", useful for XML/HTML
nnoremap <leader>ft Vatzf

nmap <C-B> :CtrlPBuffer<CR>

" Split the buffer or window left, right, up, or down
nmap <leader>sh  :leftabove  vnew<CR>
nmap <leader>sj  :rightbelow new<CR>
nmap <leader>sk  :leftabove  new<CR>
nmap <leader>sl  :rightbelow vnew<CR>
nmap <leader>swh :topleft    vnew<CR>
nmap <leader>swj :botright   new<CR>
nmap <leader>swk :topleft    new<CR>
nmap <leader>swl :botright   vnew<CR>

" }}}

" Custom commands {{{

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
command! DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
        \ | wincmd p | diffthis

" This doesn't work right....
if &term == "screen" || &term == "xterm"
  if &term == "screen"
    set t_ts=k
    set t_fs=\
  endif
  set title
  let &titlestring = "vim " . pathshorten(expand("%:~:.:f"))
  au BufEnter * let &titlestring = "vim " . pathshorten(expand("%:~:.:f"))
endif

" Resize my window to fit N columns of 81 columns with 4 gutter columns each
" plus (n - 1) separator bars, and be max height
function! SetCols(n)
  let cols = a:n * 86 - 1
  exec "set columns=" . cols . " lines=999"
endfunction
command! -count=1 Cols call SetCols(<count>)

" Use git to find files
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard']

augroup insert_trailingspace " {{{
  au!

  " Remove trailing spaces when leaving insert mode
  au InsertLeave * '[,']s/\s\+$//e|normal `^
augroup END " }}}

augroup jump_to_last_pos " {{{
  au!
  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif
augroup END " }}}

augroup grep " {{{
  au!
  " Automatically open the grep window after performing a grep.
  autocmd QuickFixCmdPost *grep* cwindow
augroup END " }}}

" }}}

" File type-specific {{{

augroup ft_phpt " {{{
  au!

  " phpt files are php files in disguise
  au BufNewFile,BufRead *.phpt setlocal filetype=php
augroup END " }}}

augroup ft_javascript " {{{
  au!

  " Add ES6 yield to highlight
  au FileType javascript syn match javaScriptOperator /\<yield\>/

  " CommonJS modules omit the .js, so this allows gf to work
  au FileType javascript setlocal suffixesadd=.js
  au FileType javascript iab <buffer> jsx <F2>/** @jsx React.DOM */<CR>
    \var React = require('react-tools/build/modules/React');<CR>
    \<CR>
    \var <C-R>=expand('%:t:r')<CR> = React.createClass({<CR>
    \  render: function() {<CR>
    \    return (<CR>
    \     <CR>
    \    );<CR>
    \  }<CR>
    \});<CR>
    \<CR>
    \module.exports = <C-R>=expand('%:t:r')<CR>;<F2><Up><Up><Up><Up><Up>
augroup END " }}}

augroup ft_text " {{{
  au!

  " For all text files set 'textwidth' to 78 characters.
  au FileType text setlocal textwidth=78
augroup END " }}}

augroup ft_cfolding " {{{
  au!

  au FileType javascript,java,c,php,css setlocal foldmethod=marker
  au FileType javascript,java,c,php,css setlocal foldmarker={,}
  au FileType javascript,java,c,php,css setlocal foldlevel=999
augroup END " }}}

augroup ft_python " {{{
  au!

  au FileType python setlocal sw=4 sts=4 ts=4
augroup END " }}}

augroup ft_ruby " {{{
  au!

  au FileType ruby setlocal foldmethod=marker
augroup END " }}}

" }}}
