[aliases]
prepare = ["util", "exec", "--", "sh", "-c", 'exec "$HOME/.config/jj/Argcfile.sh" prepare "$@"', ""]
gh-pr = ["util", "exec", "--", "sh", "-c", 'exec "$HOME/.config/jj/Argcfile.sh" gh-pr "$@"', ""]
mkdir = ["util", "exec", "--", "sh", "-c", 'exec "$HOME/.config/jj/Argcfile.sh" mkdir "$@"', ""]
