#!/bin/bash
set -ue

url="${1:?Usage: xdg-open URL}"

if [[ "${VSCODE_PROXY_URI+1}" ]] && [[ "$url" =~ ^http://localhost:([0-9]+)(.*)$ ]]; then
	port="${BASH_REMATCH[1]}"
	rest="${BASH_REMATCH[2]}"
	base="${VSCODE_PROXY_URI/\{\{port\}\}/$port}"
	url="$base/$rest"
fi

url="$(echo -n "$url" | base64 -w 0)"
printf "\033]1337;OpenURL=:%s\a" "$url" >/dev/tty
