#:schema https://jj-vcs.github.io/jj/latest/config-schema.json
# the default config is available at
# https://github.com/jj-vcs/jj/blob/main/cli/src/config/

[user]
name = "Ryan Patterson"
email = "cgamesplay@cgamesplay.com"

[ui]
# Default command. Shows commits that aren't in the main branch yet.
default-command = ["util", "exec", "--", "sh", "-c", 'jj default-log "$@" && jj default-status --ignore-working-copy "$@"', ""]
log-synthetic-elided-nodes = true
# NOTE: jj exits on ^C even when the pager is active; this is not related to
# using delta.
pager = ["delta", "--pager=less -FR"]
# We have to run delta separately to actually generate the diffs, to handle
# jj's graph display.
diff-formatter = "delta"
diff-editor = "hunk"

[git]
private-commits = "private()"
fetch = ['regex:"origin|upstream"']

[colors]
commit_id = "magenta"
change_id = "blue"
"working_copy commit_id" = "bright magenta"
"working_copy change_id" = "bright blue"
"normal change_id" = { bold = true, fg = "cyan" }
"immutable change_id" = { bold = false, fg = "bright blue" }
empty = "bright black"
"working_copy empty" = "bright black"
"status diff modified" = "blue"
"status diff added" = "blue"
"status diff removed" = "blue"
"description continuation" = "bright black"

[merge-tools.hunk]
program = "jj-hunk-editor"
diff-args = []

[merge-tools.difft]
diff-args = ["--color=always", "--display=inline", "--byte-limit=100000", "$left", "$right"]
edit-args = []

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]
program = "sh"
# Delta ordinarily tries to query the terminal to determine light/dark mode,
# but it can't do that when it isn't the pager. This combines with the light
# feature (in my git config) to implement COLORFGBG, which arguably Delta
# should support natively (but doesn't).
diff-args = ["-c", """
if [ "${COLORFGBG:-0;15}" = "0;15" ]; then
  export DELTA_FEATURES="${DELTA_FEATURES+$DELTA_FEATURES }+light"
fi
exec delta "$@"
""", "", "$left", "$right"]
edit-args = []

[merge-tools.vimdiff]
program = "nvim"
diff-args = []
edit-args = []
merge-args = [
    "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
    "-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true

# Commands that typically show diffs will use delta as a pager
[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
pager = "delta"

# The default status output is a disorienting rainbow of colors
[[--scope]]
--when.commands = ["status"]
[--scope.colors]
"diff modified" = "blue"
"diff added" = "blue"
"diff removed" = "blue"

[aliases]
e = ["edit"]
# Log, but shorter.
l = ["log", "-T", "log_oneline"]
# Which revision is responsible for causing the problem I'm dealing with.
blame = ["file", "annotate"]
# The official name for "rebase" feels like historical baggage.
move = ["rebase"]
# Diff with side-by-side view
diff-sbs = ["util", "exec", "--", "sh", "-c", 'DELTA_FEATURES=+side-by-side exec jj diff "$@"', ""]

# These two commands, back-to-back, are the default command for jj.
default-log = ["log", "-T", "log_oneline", "--no-pager", "--reversed", "-r", "default_log()"]
default-status = ["log", "--no-pager", "-r", "@", "-GT", '''
  surround("\n", "", separate("\n",
    if(diff.files().len() > 0,
      join("\n",
        "Modified files in working copy:\n" ++
        indent("  ", label("status", diff.summary()))),
      "The working copy has no changes.\n"),
    if(conflicted_files.len() > 0,
      label("warning", label("heading", "Warning: ") ++ "There are unresolved conflicts at these paths:") ++ "\n" ++
      label("conflict", indent("  ", conflicted_files.map(|f|
        f.path().display() ++
        if(f.conflict_side_count() > 2,
          label("conflict_description difficult", " [" ++ f.conflict_side_count() ++ "-way]"))
      ).join("\n"))))
  ))
''']

# Interactively select an operation to restore
rewind = ["util", "exec", "--", "sh", "-c", '''
choice=$(jj op log --color=always -G -T \
  'concat(id, "\x07", separate(" ", id.short(), format_short_timestamp(time.start()), description), "\0")' | \
  fzf --read0 --ansi --delimiter='\07' --with-nth=2 --accept-nth=1 \
  --preview='jj --color=always --at-op={1}' \
  --preview-window="right:40%")
if [ $? -eq 0 ]; then
  jj op restore "$choice"
fi
''', "rewind"]

# Move all staged changes into the parent change (requires manually adding
# changes to the git index).
squash-index = ["util", "exec", "--", "sh", "-c", """
set -e
if git diff-index --quiet --cached HEAD --; then
  echo "Nothing to do" >&2
  exit 1
fi
current_change=$(jj log --no-graph -r @ -T change_id)
tree=$(git write-tree)
jj edit @- --quiet
git restore --source="$tree" -WS -- :/
git ls-files -z --cached :/ | xargs -0 jj file track
jj edit "$current_change"
""", "jj squash-index"]
# Move all unstaged changes into a new child change (requires manually adding
# changes to the git index).
split-index = ["util", "exec", "--", "sh", "-c", """
set -e
cd "$JJ_WORKSPACE_ROOT"
unstaged_diff=$(git diff)
git checkout -- .
jj new --quiet
if [ ! -z "$unstaged_diff" ]; then
  echo "$unstaged_diff" | patch -p1 >/dev/null
  echo "Unstaged changes moved into child change."
fi
jj status
""", "jj split-index"]

[revsets]
# Default revset works just like `git log`
log = '::@'
# Give mutable commits shorter prefixes
short-prefixes = 'mutable()'

[revset-aliases]
# NOTE: revset-aliases shadow bookmarks, so it's generally a good idea to
# always use the function form.

'default_log()' = "ancestors(trunk()..mutable(), 2)"

# Private and WIP commits that should never be pushed anywhere. Often part of
# work-in-progress merge stacks.
'private()' = "description(glob:'wip:*' | glob:'private:*')"

# Find the latest "pushable" commit to the given one. Pushable means that all
# ancestors are pushable.
'closest_pushable(to)' = 'heads(..to ~ unpushable()::)'
'unpushable()' = 'mutable() & (description(exact:"") | (empty() & ~merges()) | conflicts() | private())'
# Find the latest bookmark in the history leading to the given revs.
'closest_bookmark(to)' = 'heads(::to & tracked_remote_bookmarks())'

[templates]
log = 'log_detailed'

log_node = '''
label('node',
  coalesce(
    if(!self, label('elided', '⋮')),
    label(
      separate(' ',
        if(current_working_copy, 'working_copy'),
        if(immutable, 'immutable', 'mutable'),
        if(conflict, 'conflicted'),
        if(self.contained_in('private()'), 'private'),
      ),
      coalesce(
        if(current_working_copy, '@'),
        if(immutable, '◆'),
        if(self.contained_in('unpushable()'), '⊗'),
        if(conflict, '×'),
        '○',
      )
    )
  )
)
'''

[template-aliases]

shell_prompt = '''
separate(' ',
  coalesce(
    if(hidden, label('hidden', change_id.shortest(4) ++ ' hidden')),
    if(divergent, label('divergent', change_id.shortest(4) ++ '??')),
    change_id.shortest(4),
  ),
  commit_id.shortest(4),
  coalesce(
    if(conflict, label('conflict', '(conflict)')),
    if(empty, label('empty', '(empty)')),
  ),
  label("diff modified", count_if_present("~", diff.files().filter(|f| f.status() == "modified" || f.status() == "renamed").len())),
  label("diff added", count_if_present("+", diff.files().filter(|f| f.status() == "added" || f.status() == "copied").len())),
  label("diff removed", count_if_present("-", diff.files().filter(|f| f.status() == "removed").len())),
  coalesce(truncate_end(24, description.first_line(), '…'), description_placeholder),
)
'''
'count_if_present(prefix, value)' = 'if(value != 0, prefix ++ value)'

log_oneline = 'log_oneline(self)'
'log_oneline(commit)' = '''
if(commit.root(),
  format_root_commit(commit),
  label(
    separate(' ',
      if(commit.current_working_copy(), 'working_copy'),
      if(commit.immutable(), 'immutable', 'mutable'),
      if(commit.conflict(), 'conflicted'),
    ),
    concat(
      separate(' ',
        format_short_change_id_with_change_offset(commit),
        format_short_commit_id(commit.commit_id()),
        format_short_timestamp(commit_timestamp(commit)),
        surround( '[', ']', separate(', ',
            commit.bookmarks().join(", "),
            commit.tags().join(", "))),
        commit.working_copies(),
        format_short_signature_oneline(commit.author()),
        if(commit.conflict(), label('conflict', 'conflict')),
        if(config('ui.show-cryptographic-signatures').as_boolean(),
          format_short_cryptographic_signature(commit.signature())),
        if(commit.empty(), label('empty', '(empty)')),
        format_description_oneline(commit),
      ) ++ "\n",
    ),
  )
)
'''

log_detailed = 'log_detailed(self)'
'log_detailed(commit)' = '''
concat(
  "Commit ID: " ++ commit.commit_id().shortest(100) ++ "\n",
  "Change ID: " ++ commit.change_id().shortest(100) ++ "\n",
  surround("Bookmarks: ", "\n", separate(" ",
    commit.local_bookmarks(),
    commit.remote_bookmarks().map(|b| format_bookmark_hyperlink(b)))),
  surround("Tags     : ", "\n", commit.tags()),
  "Author   : " ++ format_detailed_signature(commit.author()) ++ "\n",
  "Committer: " ++ format_detailed_signature(commit.committer())  ++ "\n",
  if(config("ui.show-cryptographic-signatures").as_boolean(),
    "Signature: " ++ format_detailed_cryptographic_signature(commit.signature()) ++ "\n"),
  "\n",
  indent("    ",
    if(commit.description(),
      commit.description().trim_end(),
      label(if(commit.empty(), "empty"), description_placeholder)) ++ "\n"),
  "\n",
)
'''

'format_short_commit_header(commit)' = 'log_oneline(commit)'

'format_description_oneline(commit)' = '''
  label("description", if(commit.description(),
    separate(" ",
      commit.description().first_line(),
      label("continuation", if(commit.description().lines().len() > 1, "[…]"))),
    label(if(commit.empty(), 'empty'), description_placeholder),
  ))
'''

'format_short_signature_oneline(signature)' = '''
if(signature.email() != config('user.email').as_string(),
  coalesce(signature.email().local(), email_placeholder))
'''
# "YYYY-MM-DD" is 10 characters, and the longest value this can print
'format_short_timestamp(timestamp)' = '''
pad_end(10, if(timestamp.after('1 week ago'),
  timestamp.ago().replace(regex:' (.).* ago', '$1 ago'),
  timestamp.format('%F')
  ))
'''
'format_timestamp(timestamp)' = "timestamp.format('%+')"

'format_bookmark_hyperlink(b)' = '''
  hyperlink(url_bookmark(git_web_url(b.remote()), b),
      b.name() ++ surround(" (", ")", separate(" ",
        b.synced()
      ))
)
'''

'url_bookmark(base_url, b)' = '''coalesce(
  if(base_url.contains('github.com'), base_url ++ '/tree/' ++ b.name()),
  if(base_url.contains('gitlab.com'), base_url ++ '/tree/' ++ b.name()),
  base_url
)'''
'url_tag(base_url, t)' = 'base_url'

# vim:sw=2
