#!/bin/bash
touch "$ALTGIT_PRIMARY/info/exclude"
sed -i '' '/# BEGIN ALTGIT/,/# END ALTGIT/d' "$ALTGIT_PRIMARY/info/exclude"
cat >>"$ALTGIT_PRIMARY/info/exclude" <<EOF
# BEGIN ALTGIT
# Lines in this section are automatically managed by altgit.
$(git rev-parse --path-format=relative --git-dir)
$(git ls-files)
# END ALTGIT
EOF
