#!/bin/bash
matches="$(altgit primary-exec ls-files | grep -Fxf <(altgit diff --name-only --cached))"
if [ ! -z "$matches" ]; then
    echo 'The following files are tracked in the primary git and should not be added to altgit:' >&2
    printf "%s\n" "$matches" >&2
    exit 1
fi
