[[snippets]]
  description = "get WAN IP address"
  command = "curl ifconfig.co"
  tag = ["network", "ifconfig"]
  output = ""

[[snippets]]
  description = "start VM"
  command = "/Applications/VMware\\ Fusion.app/Contents/Library/vmrun start <vmx='/Users/rpatterson/Documents/Virtual Machines.localized/Freelancing.vmwarevm/Freelancing.vmx'> gui"
  tag = ["vmware"]
  output = ""

[[snippets]]
  description = "stop VM"
  command = "/Applications/VMware\\ Fusion.app/Contents/Library/vmrun stop <vmx='/Users/rpatterson/Documents/Virtual Machines.localized/Freelancing.vmwarevm/Freelancing.vmx'>"
  tag = ["vmware"]
  output = ""

[[snippets]]
  description = "get VM guest IP address"
  command = "/Applications/VMware\\ Fusion.app/Contents/Library/vmrun getGuestIPAddress <vmx='/Users/rpatterson/Documents/Virtual Machines.localized/Freelancing.vmwarevm/Freelancing.vmx'>"
  tag = ["vmware"]
  output = ""

[[snippets]]
  description = "Run command when files change in paths"
  command = "fswatch -or0 <paths=.> | xargs -0 -n 1 -I {} <command>"
  output = ""

[[snippets]]
  description = "Show the shared objects used by the binary."
  command = "otool -L <binary>"
  tag = ["macos"]
  output = ""

[[snippets]]
  description = "Stash; rebase; push to master; pop stash"
  command = "git stash && git pull && git push <origin=origin> <branch> && git stash pop"
  tag = ["common"]
  output = ""

[[snippets]]
  description = "List indexes in ElasticSearch"
  command = "http -v <elasticsearch_host=http://10.254.0.1:9200/>_aliases"
  output = ""
